config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'employees#index'

  resources :skills
  resources :sectors
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :sector
	
	has_many :employee_skill
	has_many :skill, through: :employee_skill
	
	validates_presence_of :name
	
	def self.search(query)
		where(["name LIKE ?", "%#{query}%"])
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /employees
  # GET /employees.json
  def index
	if params[:search]
		@employees = Employee.search(params[:search])
	else
		@employees = Employee.all
	end

    @employees = @employees.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :age, :role, :active, :sector_id, :skill_ids => [])
    end

	def sort_column
	  Employee.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
	  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sector %>
    <%= collection_select(:employee, :sector_id, Sector.all, :id, :name, {}, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, id: :employee_age, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :role %>
    <%= form.text_field :role, id: :employee_role, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :skill %>
    <%= collection_check_boxes(:employee, :skill_ids, Skill.all, :id, :name) do |b| %>
	<%= b.label(class:"label-checkbox") { b.check_box + b.text } %>
	<% end %>
  </div>

  <div class="form-group">
    <%= form.label :active %>
    <%= form.check_box :active, id: :employee_active %>
  </div>

  <div class="actions">
	<%= link_to employees_path, :class => "btn btn-default" do %>
		<i class="fa fa-arrow-left"></i> Back
	<% end %>
    <%= button_tag type: 'submit', class: 'btn btn-success' do %>
		<i class="fa fa-hdd-o"></i> Save
	<% end %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h2>Edit Employee</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', employee: @employee %>
		</div>
	</div>
</div>

app/views/employees/index.html.erb
<h2>Employees</h2>

<%= link_to new_employee_path, :class => "btn btn-success" do %>
	<i class="fa fa-plus"></i> New Employee
<% end %>

<div class="search-right">
	<%= form_tag employees_path, :method => :get do %>
		<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search by Name" %>
		<%= button_tag type: "submit", class: "btn btn-success" do %>
			<i class="fa fa-search"></i>
		<% end %>
	<% end %>
</div>

<% if @employees.length == 0 %>
	<div class="alert alert-warning">No items registered</div>
<% else %>
	<table class="table table-bordered table-striped">
	  <thead>
		<tr>
		  <th scope="col"><%= sortable "sector.name", "Sector" %></th>
		  <th scope="col"><%= sortable "name" %></th>
		  <th scope="col"><%= sortable "age" %></th>
		  <th scope="col"><%= sortable "role" %></th>
		  <th scope="col"><%= sortable "active" %></th>
		  <th scope="col" class="col-actions">Actions</th>
		</tr>
	  </thead>
	  <tbody>
		<% @employees.each do |employee| %>
		  <tr>
			<td><%= employee.sector.name %></td>
			<td><%= employee.name %></td>
			<td><%= employee.age %></td>
			<td><%= employee.role %></td>
			<td><%= employee.active %></td>
			<td class="text-center">
				<%= link_to employee, :class => "btn btn-default" do %>
					<i class="fa fa-eye"></i> Show
				<% end %>
				<%= link_to edit_employee_path(employee), :class => "btn btn-primary" do %>
					<i class="fa fa-edit"></i> Edit
				<% end %>
				<%= link_to employee, method: :delete, data: { confirm: "Are you sure you want to remove?" }, :class => "btn btn-danger" do %>
					<i class="fa fa-trash"></i> Delete
				<% end %>
			</td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	<div class="pag-right">
		<%= will_paginate @employees, renderer: BootstrapPagination::Rails %>
	</div>
<% end %>

app/views/employees/new.html.erb
<h2>New Employee</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', employee: @employee %>
		</div>
	</div>
</div>

app/views/employees/show.html.erb
<h2>Employee</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Sector:</strong>
			  <%= @employee.sector.name %>
			</p>

			<p>
			  <strong>Name:</strong>
			  <%= @employee.name %>
			</p>

			<p>
			  <strong>Age:</strong>
			  <%= @employee.age %>
			</p>

			<p>
			  <strong>Role:</strong>
			  <%= @employee.role %>
			</p>

			<p>
			  <strong>Skill:</strong>
			  <ul>
				<% @employee.skill.each do |skill| %>
					<li><%= skill.name %></li>
				<% end %>
			  </ul>
			</p>

			<p>
			  <strong>Active:</strong>
			  <%= @employee.active %>
			</p>

			<br><br>
			
			<%= link_to employees_path, :class => "btn btn-default" do %> 
				<i class="fa fa-arrow-left"></i> Back
			<% end %>
			<%= link_to edit_employee_path, :class => "btn btn-success" do %> 
				<i class="fa fa-edit"></i> Edit
			<% end %>
		</div>
	</div>
</div>