config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'employees#index'

  resources :skills
  resources :sectors
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sector.rb
class Sector < ApplicationRecord
		
	validates_presence_of :name
	
	def self.search(query)
		where(["name LIKE ?", "%#{query}%"])
	end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /sectors
  # GET /sectors.json
  def index
    if params[:search]
		@sectors = Sector.search(params[:search])
	else
		@sectors = Sector.all
	end

	@sectors = @sectors.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to sectors_url, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to sectors_url, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name)
    end

	def sort_column
	  Sector.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
	  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_with(model: sector, local: true) do |form| %>
  <% if sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sector_name, class: 'form-control' %>
  </div>

  <div class="actions">
	<%= link_to sectors_path, :class => "btn btn-default" do %>
		<i class="fa fa-arrow-left"></i> Back
	<% end %>
    <%= button_tag type: 'submit', class: 'btn btn-success' do %>
		<i class="fa fa-hdd-o"></i> Save
	<% end %>
  </div>
<% end %>

app/views/sectors/edit.html.erb
<h2>Edit Sector</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', sector: @sector %>
		</div>
	</div>
</div>

app/views/sectors/index.html.erb
<h2>Sectors</h2>

<%= link_to new_sector_path, :class => "btn btn-success" do %>
	<i class="fa fa-plus"></i> New Sector
<% end %>

<div class="search-right">
	<%= form_tag sectors_path, :method => :get do %>
		<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search by Name" %>
		<%= button_tag type: "submit", class: "btn btn-success" do %>
			<i class="fa fa-search"></i>
		<% end %>
	<% end %>
</div>

<% if @sectors.length == 0 %>
	<div class="alert alert-warning">No items registered</div>
<% else %>
	<table class="table table-bordered table-striped">
	  <thead>
		<tr>
		  <th scope="col"><%= sortable "name" %></th>
		  <th scope="col" class="col-actions">Actions</th>
		</tr>
	  </thead>
	  <tbody>
		<% @sectors.each do |sector| %>
		  <tr>
			<td><%= sector.name %></td>
			<td class="text-center">
				<%= link_to sector, :class => "btn btn-default" do %>
					<i class="fa fa-eye"></i> Show
				<% end %>
				<%= link_to edit_sector_path(sector), :class => "btn btn-primary" do %>
					<i class="fa fa-edit"></i> Edit
				<% end %>
				<%= link_to sector, method: :delete, data: { confirm: "Are you sure you want to remove?" }, :class => "btn btn-danger" do %>
					<i class="fa fa-trash"></i> Delete
				<% end %>
			</td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	<div class="pag-right">
		<%= will_paginate @sectors, renderer: BootstrapPagination::Rails %>
	</div>
<% end %>

app/views/sectors/new.html.erb
<h2>New Sector</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', sector: @sector %>
		</div>
	</div>
</div>

app/views/sectors/show.html.erb
<h2>Sector</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Name:</strong>
			  <%= @sector.name %>
			</p>

			<br><br>
			
			<%= link_to sectors_path, :class => "btn btn-default" do %> 
				<i class="fa fa-arrow-left"></i> Back
			<% end %>
			<%= link_to edit_sector_path, :class => "btn btn-success" do %> 
				<i class="fa fa-edit"></i> Edit
			<% end %>
		</div>
	</div>
</div>