config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root 'employees#index'

  resources :skills
  resources :sectors
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord
		
	validates_presence_of :name
	
	def self.search(query)
		where(["name LIKE ?", "%#{query}%"])
	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /skills
  # GET /skills.json
  def index
    if params[:search]
		@skills = Skill.search(params[:search])
	else
		@skills = Skill.all
	end

	@skills = @skills.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to skills_url, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to skills_url, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name)
    end

	def sort_column
	  Skill.column_names.include?(params[:sort]) ? params[:sort] : "name"
	end

	def sort_direction
	  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :skill_name, class: 'form-control' %>
  </div>

  <div class="actions">
	<%= link_to skills_path, :class => "btn btn-default" do %> 
		<i class="fa fa-arrow-left"></i> Back
	<% end %>
    <%= button_tag type: 'submit', class: 'btn btn-success' do %> 
		<i class="fa fa-hdd-o"></i> Save
	<% end %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h2>Edit Skill</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', skill: @skill %>
		</div>
	</div>
</div>

app/views/skills/index.html.erb
<h2>Skills</h2>

<%= link_to new_skill_path, :class => "btn btn-success" do %>
	<i class="fa fa-plus"></i> New Skill
<% end %>

<div class="search-right">
	<%= form_tag skills_path, :method => :get do %>
		<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search by Name" %>
		<%= button_tag type: "submit", class: "btn btn-success" do %>
			<i class="fa fa-search"></i>
		<% end %>
	<% end %>
</div>

<% if @skills.length == 0 %>
	<div class="alert alert-warning">No items registered</div>
<% else %>
	<table class="table table-bordered table-striped">
	  <thead>
		<tr>
		  <th scope="col"><%= sortable "name" %></th>
		  <th scope="col" class="col-actions">Actions</th>
		</tr>
	  </thead>
	  <tbody>
		<% @skills.each do |skill| %>
		  <tr>
			<td><%= skill.name %></td>
			<td class="text-center">
				<%= link_to skill, :class => "btn btn-default" do %>
					<i class="fa fa-eye"></i> Show
				<% end %>
				<%= link_to edit_skill_path(skill), :class => "btn btn-primary" do %>
					<i class="fa fa-edit"></i> Edit
				<% end %>
				<%= link_to skill, method: :delete, data: { confirm: "Are you sure you want to remove?" }, :class => "btn btn-danger" do %>
					<i class="fa fa-trash"></i> Delete
				<% end %>
			</td>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	<div class="pag-right">
		<%= will_paginate @skills, renderer: BootstrapPagination::Rails %>
	</div>
<% end %>

app/views/skills/new.html.erb
<h2>New Skill</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<%= render 'form', skill: @skill %>
		</div>
	</div>
</div>

app/views/skills/show.html.erb
<h2>Skill</h2>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="container-form col-sm-5">
			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Name:</strong>
			  <%= @skill.name %>
			</p>

			<br><br>
			
			<%= link_to skills_path, :class => "btn btn-default" do %> 
				<i class="fa fa-arrow-left"></i> Back
			<% end %>
			<%= link_to edit_skill_path, :class => "btn btn-success" do %> 
				<i class="fa fa-edit"></i> Edit
			<% end %>
		</div>
	</div>
</div>